title: David Cook's Blog
email: divergentdave@gmail.com
description: >-
  David Cook's blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: divergentdave
github_username:  divergentdave

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "David Cook"
