title: David Cook's Blog
email: divergentdave@gmail.com
description: >-
  David Cook's blog
baseurl: ""
url: "https://davidsherenowitsa.party"
twitter_username: divergentdave
github_username:  divergentdave

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "David Cook"
